### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by DanielChuDC** [leafgecko/NTULearn-Downloader#1]
```
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    bbrouter = authenticate(args.username, args.password)
  File "/Users/danielchu/Documents/GitHub/NTULearn-Downloader/ntu_learn_downloader/api.py", line 90, in authenticate
    raise Exception(
Exception: Bbrouter: expires:XXXXXXXXXXXXXX,signature:XXXXXXXXXXXXXX,site:XXXXXXXXXXXXXXX,v:2,xsrf:XXXXXXXXXXX does not have user field, it is not authenticated
```

**Comment by leafgecko** [comment]
Hi this appears to be a log in error. For your username you are required to put in the full student email (xxx@student.main.ntu.edu.sg) followed by your ntulearn password.

Let me know if the issues persist

**Comment by DanielChuDC** [comment]
yup I had tried multiple times with the full student email and even double checked with the blackboard UI but no luck

**Comment by DanielChuDC** [comment]
Do you mind checking this issue? @leafgecko see if you can login? I only trying to login with the `main.py`. 

`python main.py -u <username> -p <password>`

**Comment by leafgecko** [comment]
I'll check that and let you know soon. In the meantime, if its possible for you, could you try the GUI versions and see if there is a log in error for you there?
Thank you

**Comment by DanielChuDC** [comment]
sure

**Comment by leafgecko** [comment]
hi I'm able to log in with my credentials. in the above format `python main.py -u <username> -p <password>`  I'm slightly suspecting it is a python issue. Could you try `python3` instead of `python`?

**Comment by DanielChuDC** [comment]
I am actually using python 3.8 and i link the command `python3` as `python` in my mac. That is weird. I have checked all correct account username and password

**Comment by DanielChuDC** [comment]
should we use python 2 or python 3 to run the `main.py`?

**Comment by DanielChuDC** [comment]
By using GUI, I am able to login into the portal. interesting

**Comment by leafgecko** [comment]
my `python` maps to `Python 3.7.6`.
we should use python 3 to run it. Admittedly I have not done testing using python 2, nd i don't think we plan to support it. (Since python 2 has hit it's end of life)

**Comment by DanielChuDC** [comment]
I see. I am using 'python 3.8.6'
. Not sure if this is the error

**Comment by leafgecko** [comment]
A few possibilities are
1. password has weird special characters that the terminal handles incorrectly
2. issue with using application python 3.8

for 2 i would be able to get that tested, but I'll likely get back to you on that tomorrow if that's okay

**Comment by DanielChuDC** [comment]
No worry. Take your time.👍

**Comment by leafgecko** [comment]
thanks for taking the time to report this issue

**Comment by DanielChuDC** [comment]
thanks for the awesome project.

**Comment by DanielChuDC** [comment]
@leafgecko I finally got in! My password contains weird character! I had to add in `'` single quote in order to login! your guess is right! Thanks for the support. Gonna close this issue.

**Comment by leafgecko** [comment]
That's good to know, I will add a note to the read me to let users know of this potential issue. Hope you enjoy NTULearn Downloader
