### ISSUE TITLE
Recorded Lecture Downloader fails to grab .mp4 link from html

### ISSUE THREAD

**Issue by RealDyllon** [leafgecko/NTULearn-Downloader#6]
When attempting to download recorded lectures, the html parser fails to grab the .mp4 link to the lecture.

Below is the shell output from the script:

```bash
❯ python main.py --sem 20S2 -username $NTU_USERNAME -password $NTU_PW --download_to NTU --download_recorded_lectures
you are taking the following courses:
- 20S2-CE1106-CZ1106-C-LEC (20S2-CE1106-CZ1106-COMPUTER ORGANISATION & ARCHIT)
- 20S2-CE1107-CZ1107-C-LEC (20S2-CE1107-CZ1107-DATA STRUCTURES & ALGORITHMS)
- 20S2-ET0001-LEC (ET0001-ENTERPRISE & INNOVATION)
- 20S2-CE1104-CZ1104-C-LEC (20S2-CE1104-CZ1104-LINEAR ALGEBRA FOR COMPUTING)
- 20S2-CE1115-CZ1115-C-LEC (20S2-CE1115-CZ1115-INTRO TO DATA SCI & ART INTELL)
- 20S2-EG0001-C-LEC (20S2-EG0001-ENGINEERS & SOCIETY)
- 20S2-EG0001-TUT-EG05 (20S2-EG0001-ENGINEERS & SOCIETY (TUT GP5))
- 20S2-MA1002-LEC-LE (20S2-MAE-MA1002-FUNDAMENTAL ENG MATERIALS - FT)
- 20S2-MA1002-TUT-MA9 (20S2-MAE-MA1002-FUNDAMENTAL ENG MATERIALS (TUT) - MA9)
- LIB-IML_AY2020 (LIB-IML_AY2020: Information & Media Literacy (AY2020/21))
- SLO-AY2020 (AY 2020 Student Life Modules)


Downloading to NTU
20S2-CE1106-CZ1106-C-LEC (20S2-CE1106-CZ1106-COMPUTER ORGANISATION & ARCHIT)
Traceback (most recent call last):
  File "/Users/dyllon/NTULearn-Downloader/main.py", line 192, in <module>
    download_files(
  File "/Users/dyllon/NTULearn-Downloader/main.py", line 77, in download_files
    download_files(
  File "/Users/dyllon/NTULearn-Downloader/main.py", line 77, in download_files
    download_files(
  File "/Users/dyllon/NTULearn-Downloader/main.py", line 77, in download_files
    download_files(
  [Previous line repeated 2 more times]
  File "/Users/dyllon/NTULearn-Downloader/main.py", line 109, in download_files
    download_link = get_recorded_lecture_download_link(
  File "/Users/dyllon/NTULearn-Downloader/ntu_learn_downloader/api.py", line 233, in get_recorded_lecture_download_link
    return parse_recorded_lecture_contents(html)
  File "/Users/dyllon/NTULearn-Downloader/ntu_learn_downloader/parsing.py", line 14, in parse_recorded_lecture_contents
    raise ValueError('Unable to get mp4 download link')
ValueError: Unable to get mp4 download link
```

Let me know if you need any further information to triage this bug.

**Comment by raynoldng** [comment]
Hi @RealDyllon! Thank you for filing the bug report. Supporting video downloads is tricky as NTU Learn seems to constantly change how their videos are being loaded. Could I trouble you to dump the html text that was being parsed?

You can do that by adding a `print(html)` to this line: https://github.com/leafgecko/NTULearn-Downloader/blob/master/ntu_learn_downloader/parsing.py#L14

In the meantime, we will try to improve the robustness of the parsing logic and error reporting so that we can fix the problem quickly. 

Cheers and HNY

**Comment by leafgecko** [comment]
On another note, we have talked about this issue and decided that ideally we should offload the loading of mp4 links to a server, to minimise users having to keep making bug reports of this nature. It will be easier for us to detect problems and fix them internally.

**Comment by RealDyllon** [comment]
Hey @raynoldng and @leafgecko, apologies for the delayed reply. Gave the script a spin earlier this week, and the downloader worked fine, without code changes.

Since this seems like a one-of thing, I'm going to close the issue.

Thanks, and all the best for next semester!

**Comment by leafgecko** [comment]
No worries thank you for using this application! We hope you will continue to find this useful
